# ----------------------------------------
# GitHub Actions Part-1  -  Basic
#
# Copyleft (c) by Me 2025
# ----------------------------------------
name: My-GitHub-Actions-Basics
env:
  APPLICATION_NAME   : "MyCombo"
  DEPLOY_PACAGE_NAME : "Combo_deploy_ver_${{ github.sha }}"
  
on: 
  push:
    branches: 
        - main

jobs: 
  my_testing: 
    runs-on : ubuntu-latest
    
    steps: 
      - name: Print Hello message
        run : echo "Hello Yopta from testing job!"  

      - name: Execute few commands 
        run :
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name ${{ env.APPLICATION_NAME }}"

      - name: List current folder
        run : ls -la 

      - name: Git clone my repo
        uses: actions/checkout@v3 

      - name: List current folder
        run : ls -la 

  my_deploy:
    runs-on: ubuntu-latest 
    needs  : [my_testing]
    env:
      VAR_1 : "This is Job lev. 1 Var. 1"
      VAR_2 : "This is Job lev. 1 Var. 2"  
    
    steps:
      - name: Print Hello message
        run : echo "Hello Yopta from deploy job!" 

      - name: Print env vars
        run : 
          echo "Var1 = S{{ env.VAR_1 }}"
          echo "Var2 = S{{ env.VAR_2 }}"
          echo "Var3 = SLOCAL_VAR"
        env:
          LOCAL_VAR: "Surep local raviable"

      - name: Printing Deployment package
        run : echo "Deploy package is ${{ env.DEPLOY_PACAGE_NAME }}"

      - name: Lest test some packages if they are here 1
        run : aws --version

      - name: Lest test some packages if they are here 2
        run : zip --version
  
  
